export const siteConfig = {
  name: "Gamca Centre",
  tagline: "Get Your Medical Token",
  description:
    "Your trusted assistance for Wafid/GAMCA medical appointment token processing in Pakistan. Fast, hassle-free, and premium concierge service.",
  url: "https://www.gamcacentre.com",
  contact: {
    phone: "+923079254422",
    phoneDisplay: "+92 307 925 44 22",
    whatsapp: "+923079254422",
    whatsappUrl: "https://wa.me/923079254422",
    email: "gamcacentre9@gmail.com",
    address: "Gamca Medical Token Assistance Center, Pakistan",
    workingHours: "Monday – Saturday: 9:00 AM – 8:00 PM (PKT)",
  },
  logo: {
    src: "/logo.webp",
    srcSm: "/logo-sm.webp",
    srcFooter: "/logo-footer.webp",
    alt: "Gamca Centre – Wafid & GAMCA Medical Appointment Token Assistance Pakistan",
    width: 800,
    height: 800,
  },
  paymentInfo: {
    qrImageSrc: "/payment-qr.jpg",
    accountName: "GAMCA MEDICAL CENTRE",
    bankName: "JazzCash / Raast",
    tillId: "984433580",
    accountNumber: "984433580",
    paymentReferenceNote: "Dial *786*10# and enter TILL ID (984433580) to pay via JazzCash, or scan QR code via any Banking / Raast App.",
    feeNote: "Medical appointment token fee applies as per Wafid standards.",
  },
  destinationCountries: [
    { code: "KSA", name: "Saudi Arabia", flag: "🇸🇦" },
    { code: "UAE", name: "United Arab Emirates", flag: "🇦🇪" },
    { code: "QAT", name: "Qatar", flag: "🇶🇦" },
    { code: "KWT", name: "Kuwait", flag: "🇰🇼" },
    { code: "BHR", name: "Bahrain", flag: "🇧🇭" },
    { code: "OMN", name: "Oman", flag: "🇴🇲" },
    { code: "YEM", name: "Yemen", flag: "🇾🇪" },
  ],
  visaTypes: [
    "Employment Visa",
    "Work Visa",
    "Family Visa",
    "Residence Visa",
    "Visit / Transit Visa",
    "Other",
  ],
  positions: [
    "Worker",
    "Engineer",
    "Technician",
    "Nurse",
    "Doctor",
    "Driver",
    "Electrician",
    "Plumber",
    "Laborer",
    "Other",
  ],
  maritalStatuses: [
    "Single",
    "Married",
  ],
  genders: ["Male", "Female"],
  examinationCountryDefault: "Pakistan",
};
