export const siteConfig = {
  name: "Gamca Centre",
  tagline: "Get Your Medical Token",
  description:
    "Your trusted assistance for Wafid/GAMCA medical appointment token processing in Pakistan. Fast, hassle-free, and premium concierge service.",
  url: "https://gamcacentre.pk",
  contact: {
    phone: "+923227840807",
    phoneDisplay: "+92 322 7840807",
    whatsapp: "+923227840807",
    whatsappUrl: "https://wa.me/923227840807",
    email: "gamcacentre9@gmail.com",
    address: "Gamca Medical Token Assistance Center, Pakistan",
    workingHours: "Monday – Saturday: 9:00 AM – 8:00 PM (PKT)",
  },
  logo: {
    src: "/logo.png",
    alt: "Gamca Centre Logo",
  },
  paymentInfo: {
    tokenFee: "Rs: 4,500/-",
    qrImageSrc: "/payment-qr.png",
    accountName: "Gamca Centre Assistance",
    bankName: "Meezan Bank / EasyPaisa / JazzCash",
    accountNumber: "03227840807",
    iban: "PK00 MEZN 0000 0322 7840 8070",
    paymentReferenceNote: "Please include your Passport Number or Candidate Name in the transaction reference.",
    feeNote: "Medical appointment token fee applies as per Wafid standards.",
  },
  destinationCountries: [
    { code: "KSA", name: "Saudi Arabia", flag: "🇸🇦" },
    { code: "UAE", name: "United Arab Emirates", flag: "🇦🇪" },
    { code: "QAT", name: "Qatar", flag: "🇶🇦" },
    { code: "KWT", name: "Kuwait", flag: "🇰🇼" },
    { code: "BHR", name: "Bahrain", flag: "🇧🇭" },
    { code: "OMN", name: "Oman", flag: "🇴🇲" },
    { code: "YEM", name: "Yemen", flag: "🇾🇪" },
  ],
  visaTypes: [
    "Employment Visa",
    "Work Visa",
    "Family Visa",
    "Residence Visa",
    "Visit / Transit Visa",
    "Other",
  ],
  positions: [
    "Worker",
    "Engineer",
    "Technician",
    "Nurse",
    "Doctor",
    "Driver",
    "Electrician",
    "Plumber",
    "Laborer",
    "Other",
  ],
  maritalStatuses: [
    "Single",
    "Married",
  ],
  genders: ["Male", "Female"],
  examinationCountryDefault: "Pakistan",
};
